import Head from "next/head";
import { Inter } from "next/font/google";
import HomeModule from "@/modules/Home";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

const Home = () => (
    <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={`${styles.main} ${inter.className}`}>
            <HomeModule />
        </main>
    </>
);

export default Home;
